version: '3.8'

services:
  postgres:
    build: .
    container_name: postgres_165
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Pa$$w0rd!!!
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
      - ./pg_hba.conf:/etc/postgresql/pg_hba.conf
      - ssl_certs:/etc/postgresql/ssl
    command: postgres -c config_file=/etc/postgresql/postgresql.conf -c hba_file=/etc/postgresql/pg_hba.conf
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    name: postgres_data
  ssl_certs:
    driver: local